# What's Herbs?

Herbs is an open source library for backend applications. It is focused on achieving faster deliveries and with happier developers, without neglecting the long-term need to constantly evolve your application as requirements change.

See more on the website: [https://herbsjs.org/](https://herbsjs.org/)

# Getting Started with CLI on Herbs

Within this repository, you will find a front-end application, made in react consuming a back-end application, using [Herbs](https://github.com/herbsjs), the API is made in graphQL or rest (this will depend on what you chose during project creation)

# Herbs CLI

This is a example on how to build a backend application using [Herbs](https://github.com/herbsjs).

### Using

    $ npm install
    $ npm run knex:migrate (in case of using relational database with herbs2knex, not necessary for MongoDB)
    $ npm start

  You should receive this message => 🚀 Server UP and Running in port: 3000 (this will depend on what you chose during project creation)

### Herbs Shelf

View all the use cases and its steps in just one place.

Herbs Shelf: [http://localhost:3000/herbsshelf](http://localhost:3000/herbsshelf)

Documentation dynamically generated by [herbsshelf](https://github.com/herbsjs/herbsshelf/).

### GraphQL

GraphQL Playground: [http://localhost:3000/graphql](http://localhost:3000/graphql)

GraphQL dynamically generated by [herbs2gql](https://github.com/herbsjs/herbs2gql).

### Rest

Express routes dynamically generated  by [herbs2rest](https://github.com/herbsjs/herbs2rest).

## Contribute

Come with us to make an awesome _herbs-cli_.

Now, if you do not have the technical knowledge and also have intended to help us, do not feel shy, [click here](https://github.com/herbsjs/herbs-cli/issues) to open an issue and collaborate their ideas, the contribution may be a criticism or a compliment (why not?)

If you would like to help contribute to this repository, please see [CONTRIBUTING](https://github.com/herbsjs/herbs-cli/blob/master/.github/CONTRIBUTING.md)
