module.exports = async ({ 
    print,
    generate, 
    packageManager, 
    options: { 
        name = 'herbs-project', 
        description = 'project generated by herbs CLI S2', 
        author = 'herbs CLI', 
        license = 'MIT',
        mongo = false,
        postgres = false,
        yarn = false
    }
}) => async () => { 
    await generate({
        template: 'package.json.ejs',
        target: `package.json`,
        props: {
            name, description, author, license
        }
    })
    const packages = [
        'buchu',
        'gotu',
        'herbs2gql',
        'deepmerge',
        'graphql',
        'apollo-server-express',
        'apollo-server',
        'sugar-env',
        'dotenv',
        'herbsshelf',
        'herbs2rest',
        'graphql-tools']

    if(mongo) 
        packages.push('mongodb')
    if(postgres){
        packages.push('herbs2knex')
        packages.push('pg')
    }
    
    let opt = { force: 'npm'}
    if(yarn) {
        if(packageManager.hasYarn())
            opt = { force: 'yarn'}
        else {
            print.warn('You don\'t have yarn installed')
        }
    }
    await packageManager.add(packages, opt)
}

