module.exports = async ({
    generate,
    packageManager,
    name = 'herbs project',
    description = 'project generated by herbs CLI S2',
    author = 'herbs CLI',
    license = 'MIT' }) => async () => { 
        await generate({
            template: 'package.json.ejs',
            target: `package.json`,
            props: {
                name, description, author, license
            }
        })
        await packageManager.add(['buchu', 'gotu'], { force: 'npm'})
    }

